### ISSUE TITLE
ingest_runner falls over on non-ascii chars

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/ARCHIVE-lasair-lsst#111]
ingest_runner fails with the following error:
```
 Traceback (most recent call last):
   File "ingest_runner.py", line 49, in <module>
     rtxt = 'stderr:' + rbin.decode('ascii').rstrip()
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 31: ordinal not in range(128)
```

I think this is caused by the presence of a unicode char in the error message that ingest_runner is trying to process that can't be decoded to ascii. Changing to `rbin.decode('utf-8')` on that line appears to fix the immediate problem, but requires proper investigation and probably fixing elsewhere too.

This is the log that it appears to be choking on:
```
INGEST ---------- 2021/11/02T22:48:01
Processes = 1
ERROR in ingest/ingestBatch: Cannot connect to Cassandra
{}
eop end of messages
INGEST 0 finished with 0 alerts 0 candidates
0 alerts and 0 candidates
Tue Nov  2 22:48:06 UTC 2021
stderr:mkdir: cannot create directory ‘/mnt/cephfs’: Permission denied
stderr:%4|1635893281.962|CONFWARN|client-1#producer-2| [thrd:app]: Configuration property group.id is a consumer property and will be ignored by this producer instance
stderr:%4|1635893281.962|CONFWARN|client-1#producer-2| [thrd:app]: Configuration property session.timeout.ms is a consumer property and will be ignored by this producer instance
stderr:%4|1635893281.962|CONFWARN|client-1#producer-2| [thrd:app]: Configuration property enable.auto.commit is a consumer property and will be ignored by this producer instance
stderr:%4|1635893281.962|CONFWARN|client-1#producer-2| [thrd:app]: Configuration property auto.offset.reset is a consumer property and will be ignored by this producer instance
stderr:%3|1635893281.962|FAIL|client-1#consumer-1| [thrd:['lasair-dev-kafka-0:9092/bootstrap]: ['lasair-dev-kafka-0:9092/bootstrap: Failed to resolve '['lasair-dev-kafka-0:9092': Missing close-']' (after 0ms in state CONNECT)
stderr:%3|1635893281.963|FAIL|client-1#producer-2| [thrd:'lasair-dev-kafka-1:9092/bootstrap]: 'lasair-dev-kafka-1:9092/bootstrap: Failed to resolve ''lasair-dev-kafka-1:9092': Name or service not known (after 0ms in state CONNECT)
stderr:%3|1635893282.962|FAIL|client-1#consumer-1| [thrd:'lasair-dev-kafka-1:9092/bootstrap]: 'lasair-dev-kafka-1:9092/bootstrap: Failed to resolve ''lasair-dev-kafka-1:9092': Name or service not known (after 0ms in state CONNECT)
stderr:%3|1635893282.962|FAIL|client-1#producer-2| [thrd:['lasair-dev-kafka-0:9092/bootstrap]: ['lasair-dev-kafka-0:9092/bootstrap: Failed to resolve '['lasair-dev-kafka-0:9092': Missing close-']' (after 0ms in state CONNECT)
stderr:%3|1635893283.961|FAIL|client-1#consumer-1| [thrd:['lasair-dev-kafka-0:9092/bootstrap]: ['lasair-dev-kafka-0:9092/bootstrap: Failed to resolve '['lasair-dev-kafka-0:9092': Missing close-']' (after 0ms in state CONNECT, 1 identical error(s) suppressed)
stderr:%3|1635893283.962|FAIL|client-1#producer-2| [thrd:'lasair-dev-kafka-1:9092/bootstrap]: 'lasair-dev-kafka-1:9092/bootstrap: Failed to resolve ''lasair-dev-kafka-1:9092': Name or service not known (after 0ms in state CONNECT, 1 identical error(s) suppressed)
stderr:%3|1635893284.962|FAIL|client-1#consumer-1| [thrd:'lasair-dev-kafka-1:9092/bootstrap]: 'lasair-dev-kafka-1:9092/bootstrap: Failed to resolve ''lasair-dev-kafka-1:9092': Name or service not known (after 0ms in state CONNECT, 1 identical error(s) suppressed)
stderr:%3|1635893284.962|FAIL|client-1#producer-2| [thrd:['lasair-dev-kafka-0:9092/bootstrap]: ['lasair-dev-kafka-0:9092/bootstrap: Failed to resolve '['lasair-dev-kafka-0:9092': Missing close-']' (after 0ms in state CONNECT, 1 identical error(s) suppressed)
stderr:Traceback (most recent call last):
stderr:  File "ingest.py", line 441, in <module>
stderr:    rc = main()
stderr:  File "ingest.py", line 435, in main
stderr:    ms.add({'today_alert':nalert, 'today_candidate':ncandidate}, nid)
stderr:  File "/home/ubuntu/lasair-lsst/ingest/../utility/manage_status.py", line 113, in add
stderr:    status = self.lock_read(file_id)
stderr:  File "/home/ubuntu/lasair-lsst/ingest/../utility/manage_status.py", line 43, in lock_read
stderr:    f = open(status_file, 'w')
stderr:FileNotFoundError: [Errno 2] No such file or directory: '/mnt/cephfs/lasair/system_status/status_1766.json'
END getting more ...
```

**Comment by RoyWilliams** [comment]
Thanks Gareth. I changed decode('ascii') to decode('utf-8') in ingest/ingest_runner.py, filter/filter_runner.py, and services/TNS/tns_runner.py

**Comment by gpfrancis** [comment]
If this is done can we safely close it?

**Comment by RoyWilliams** [comment]
Thanks for pointing this out. Fixed now.
